import { ApiProperty } from '@nestjs/swagger';
import { IsEmail, IsNotEmpty, IsString } from 'class-validator';

export class LoginVerifyRequestDto {
  @ApiProperty({ description: 'User email' })
  @IsEmail()
  @IsNotEmpty()
  @IsString()
  email!: string;

  @ApiProperty({ description: 'Client proof (M1) generated by JSRP in browser' })
  @IsNotEmpty()
  @IsString()
  clientProof!: string;
}
